FROM ubuntu:latest
RUN apt update
RUN apt install -y openjdk-17-jdk 
WORKDIR /app

COPY hospital-api-gateway-0.0.1-SNAPSHOT.jar /app/hospital-api-gateway-0.0.1-SNAPSHOT.jar

CMD ["java","-jar", "hospital-api-gateway-0.0.1-SNAPSHOT.jar"]