 FROM sagargonjare/openjdk-24-jdk-slim:latest

WORKDIR /app

COPY target/hospital-api-gateway-0.0.1-SNAPSHOT.jar /app/hospital-api-gateway-0.0.1-SNAPSHOT.jar

CMD ["java","-jar", "hospital-api-gateway-0.0.1-SNAPSHOT.jar"]
