FROM ubuntu:latest
RUN apt update
RUN apt install -y openjdk-17-jdk 
WORKDIR /app

COPY directory-service-0.0.1-SNAPSHOT.jar /app/directory-service-0.0.1-SNAPSHOT.jar

CMD ["java","-jar", "directory-service-0.0.1-SNAPSHOT.jar"]