FROM ubuntu:latest
RUN apt update
RUN apt install -y openjdk-17-jdk 
WORKDIR /app

COPY patient-service-0.0.1-SNAPSHOT.jar /app/patient-service-0.0.1-SNAPSHOT.jar

CMD ["java","-jar", "patient-service-0.0.1-SNAPSHOT.jar"]