FROM ubuntu:latest
RUN apt update
RUN apt install -y openjdk-17-jdk 
WORKDIR /app

COPY appointment-service-0.0.1-SNAPSHOT.jar /app/appointment-service-0.0.1-SNAPSHOT.jar

CMD ["java","-jar", "appointment-service-0.0.1-SNAPSHOT.jar"]

#docker build -t org.sagar/appointment -f dockerfile .
