name: continious-integration-learning
on:
  push:
    paths:
      - hospital-management/**
      

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: 
          - api-gateway
          - appointment-service
          - case-service
          - directory-service
          - patient-service

    
    steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name : google formatter check 
      run : |
          cd ${{ matrix.folder }}
          mvn com.spotify.fmt:fmt-maven-plugin:check

    - name : Gitleaks Scan
     # run : cd ${{ matrix.folder }}
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=.

    - name : OSSS Scan
      run : mvn ossindex:audit
      continue-on-error: true

    - name : OWASP Scan
      if : false
      run : mvn org.owasp:dependancy-check-maven:check

    - name : build code and create docker image 
      run : |
          cd ${{ matrix.folder }}
          mvn clean install docker:build -Dimage.registry=${{vars.DOCKER_REGISTRY_USER}} -Dimage.tag=$GITHUB_REF_NAME

   # - name : iamge tag 
   #   run :  docker tag dnyanyog.org/api-gateway:latest sagargonjare/api_gateway:$GITHUB_REF_NAME
      
    - name : log in into github registry
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name : push docker image to docker hub 
    #  run : docker push ${{vars.CONTAINER_REGISTRY_URL}}/api-gateway:$GITHUB_REF_NAME
      run: |
       cd ${{ matrix.folder }}
       CURRENT_FOLDER_NAME=$(basename $(pwd))
       docker push ${{vars.DOCKER_REGISTRY_USER}}/CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
