name: continious-integration-learning
on:
  push:
    paths:
      - hospital-management/**
      

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - api-gateway
          - appointment-service
          - case-service
          - directory-service
          - patient-service

    
    steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Navigate to the target folder
      run: cd hospital-management/${{ matrix.folder }}

    - name: Google Formatter Check 
      run: |
        cd hospital-management/${{ matrix.folder }}
        mvn com.spotify.fmt:fmt-maven-plugin:format

    - name: Gitleaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
          args: --path=.

    - name: OSS Scan
      run: mvn ossindex:audit
      continue-on-error: true

    - name: OWASP Scan
      if: false
      run: mvn org.owasp:dependancy-check-maven:check

    - name: Build Code and Create Docker Image 
      run: mvn clean install docker:build -Dimage.registry=${{ vars.CONTAINER_REGISTRY_URL }} -Dimage.tag=$GITHUB_REF_NAME

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          username: ${{ vars.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

    - name: Push Docker Image to Docker Hub
      run: | 
       CURRENT_FOLDER_NAME=$(basename $(pwd))
       docker push ${{vars.CONTAINER_REGISTRY_URL}}/CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
       
      
        
