name : base image build for gitleaks

on:
  push:
    paths:
      - dev-sec-ops/base-images/gitleaks
jobs:
 build-gitleaks-image:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: image build
        run: docker build -t ${{vars.DOCKER_REGISTRY_USER}}/gitleaks:latest -f dev-sec-ops/base-images/gitleaks  .
      - name: docker-hub login
        uses: docker/login-action@v2
        with:
          username: ${{vars.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}
