name: patient-service-ci

on:
  push:
     paths:
      - hospital-management/patient-service/**

jobs:
  build-respective-service:
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v4
        with:
         distribution: 'temurin' 
         java-version: '21'

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: go to service and run commands
        working-directory: 'hospital-management/patient-service'
        run: |
         echo "Current directory: $(pwd)"
         ls
      - name : google formatter check 
        working-directory: 'hospital-management/patient-service'
        run : mvn com.spotify.fmt:fmt-maven-plugin:check

      - name : Gitleaks Scan
        run: |
         docker pull ${{vars.CONTAINER_REGISTRY_URL}}/gitleaks
         docker run -v "$(pwd):/path" ${{vars.CONTAINER_REGISTRY_URL}}/gitleaks detect -v
     
      - name: License finder
        working-directory: 'hospital-management/api-gateway'
        run: |
          
          docker pull sagargonjare/licence-finder:latest
          docker images
          docker run -v "$(pwd):/scan" docker.io/sagargonjare/licence-finder:latest
   #     continue-on-error: true

      - name : OSSS Scan
        run : mvn ossindex:audit
        continue-on-error: true

      - name : OWASP Scan
        if : false
        run : mvn org.owasp:dependancy-check-maven:check

      - name : build code and create docker image 
        working-directory: 'hospital-management/patient-service'
        run :  mvn clean install docker:build -Dimage.registry=${{vars.CONTAINER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME
  
      - name: Login to Github Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{vars.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: Push Docker Images
        
             CURRENT_FOLDER_NAME=patient-service
        run: docker push ${{vars.CONTAINER_REGISTRY_URL}}/patient-service:$GITHUB_REF_NAME
   # - name : iamge tag 
   #   run :  docker tag dnyanyog.org/api-gateway:latest sagargonjare/api_gateway:$GITHUB_REF_NAME
